export const ORDER_TYPES = {
  STOP_LOSS: "STOP_LOSS",
  TAKE_PROFIT: "TAKE_PROFIT",
  TRAILING_STOP: "TRAILING_STOP",
  OCO: "OCO",
  DCA: "DCA",
  TWAP: "TWAP",
}

export const SIDES = { BUY: "BUY", SELL: "SELL" }

export const ADDRESSES = {
  RLUSD_ISSUER: "rEG2pq6HguMSyU7rZC44fWuw75o4J5VQZs",
}
